# Vector Structure:
# [age, bmi, income, budget, smoker, hba1c, bp_systolic, has_diabetes, has_hypertension, chronic_count]

INSURANCE_PLANS = [
  {
      "id": 1,
      "link": "https://www.starhealth.in/health-insurance/arogya-sanjeevani-policy",
      "name": "Arogya Sanjeevani",
      "insurer": "Star Health",
      "type": "Basic",
      "is_family_floater": False,
      "annual_premium": 3600,
      "premium_breakdown": { "base": 3050, "gst": 550, "total": 3600 },
      "coverage": 500000,
      "pre_existing_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 5,
      "room_rent_limit": "₹5,000/day",
      "no_claim_bonus_pct": 5,
      "claim_settlement_ratio": 89,
      "hospital_network_count": 9800,
      "restoration_benefit": False,
      "ideal_vector": [25, 22.0, 400000, 500, 0, 5.2, 110, 0, 0, 0], 
      "coverage_highlights": ["Basic hospitalization covered", "AYUSH treatment up to 100%", "Cataract treatment covered"],
      "exclusions": ["Maternity", "Adventure sports", "Cosmetic surgery", "Obesity treatment"],
      "pros": ["Cheapest premium", "9,800+ hospitals", "No medical test under 45"],
      "cons": ["4-year pre-existing wait", "Low coverage ceiling", "5% co-payment on all claims"]
  },
  {
      "id": 2,
      "link": "https://www.hdfcergo.com/health-insurance/optima-secure",
      "name": "HDFC Optima Secure",
      "insurer": "HDFC ERGO",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 8200,
      "premium_breakdown": { "base": 6950, "gst": 1250, "total": 8200 },
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "No Limit",
      "no_claim_bonus_pct": 50,
      "claim_settlement_ratio": 97,
      "hospital_network_count": 13000,
      "restoration_benefit": True,
      "ideal_vector": [35, 24.0, 900000, 1000, 0, 5.5, 120, 0, 0, 0],
      "coverage_highlights": ["2X coverage from Day 1", "No room rent capping", "Unlimited restoration"],
      "exclusions": ["Maternity", "Cosmetic surgery", "Unproven treatments"],
      "pros": ["Restore benefit", "50% no-claim bonus", "Mental health covered"],
      "cons": ["2-year pre-existing wait", "No OPD cover"]
  },
  {
      "id": 3,
      "link": "https://www.starhealth.in/health-insurance/diabetes-safe-insurance-policy",
      "name": "Star Health Diabetes Safe",
      "insurer": "Star Health",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 14000,
      "premium_breakdown": { "base": 11864, "gst": 2136, "total": 14000 },
      "coverage": 500000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": True,
      "hypertension_day1": True,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 0,
      "claim_settlement_ratio": 89,
      "hospital_network_count": 9800,
      "restoration_benefit": True,
      "ideal_vector": [45, 28.0, 800000, 1500, 0, 7.5, 135, 1, 1, 1],
      "coverage_highlights": ["Day 1 coverage for Type 1 & 2 Diabetes", "Covers diabetic complications", "OPD expenses covered"],
      "exclusions": ["Non-diabetic pre-existing diseases (2-year wait)", "Maternity", "Weight loss treatments"],
      "pros": ["Diabetes covered from Day 1", "Hypertension Day 1", "OPD included"],
      "cons": ["Designed for diabetic patients only", "Lower coverage limit"]
  },
  {
      "id": 4,
      "link": "https://www.nivabupa.com/health-insurance/reassure-health-insurance.html",
      "name": "Niva Bupa ReAssure 2.0",
      "insurer": "Niva Bupa",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 11500,
      "premium_breakdown": { "base": 9745, "gst": 1755, "total": 11500 },
      "coverage": 2500000,
      "pre_existing_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Any Room",
      "no_claim_bonus_pct": 100,
      "claim_settlement_ratio": 92,
      "hospital_network_count": 10000,
      "restoration_benefit": True,
      "ideal_vector": [40, 26.0, 1500000, 1200, 1, 5.8, 128, 0, 0, 1],
      "coverage_highlights": ["ReAssure benefit unlimited times", "Age lock premium", "Day care treatments"],
      "exclusions": ["Maternity", "Hazardous sports", "Genetic disorders"],
      "pros": ["Only 1-year pre-existing wait", "₹25L coverage", "Mental health + unlimited restore"],
      "cons": ["Diabetes still has 1-year wait", "Higher premium"]
  },
  {
      "id": 5,
      "link": "https://www.careinsurance.com/product/care-supreme-health-insurance",
      "name": "Care Health Care Supreme",
      "insurer": "Care Health",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 9800,
      "premium_breakdown": { "base": 8305, "gst": 1495, "total": 9800 },
      "coverage": 1500000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 75,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 50,
      "claim_settlement_ratio": 95,
      "hospital_network_count": 11500,
      "restoration_benefit": True,
      "ideal_vector": [50, 25.0, 1000000, 1000, 0, 5.6, 125, 0, 0, 1],
      "coverage_highlights": ["Annual health check-up", "No sub-limits on advanced tech", "Unlimited automatic recharge"],
      "exclusions": ["Maternity", "Cosmetic procedures", "Self-inflicted injuries"],
      "pros": ["Covers till age 75", "Annual health checkup", "Air ambulance"],
      "cons": ["2-year pre-existing wait", "Complex claims process"]
  },
  {
      "id": 6,
      "link": "https://licindia.in/web/guest/lic-s-arogya-rakshak-plan-906-",
      "name": "LIC Arogya Rakshak",
      "insurer": "LIC",
      "type": "Senior",
      "is_family_floater": False,
      "annual_premium": 18000,
      "premium_breakdown": { "base": 15254, "gst": 2746, "total": 18000 },
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 45,
      "max_age": 80,
      "copayment_pct": 10,
      "room_rent_limit": "1% of Sum Insured",
      "no_claim_bonus_pct": 0,
      "claim_settlement_ratio": 98,
      "hospital_network_count": 5000,
      "restoration_benefit": False,
      "ideal_vector": [60, 27.0, 800000, 2000, 0, 6.0, 140, 0, 1, 2],
      "coverage_highlights": ["Defined benefit policy", "Hospital cash benefit", "Critical illness rider"],
      "exclusions": ["Pre-existing conditions under wait period", "Injuries from riot or war"],
      "pros": ["Covers till 80", "LIC brand trust", "Critical illness rider"],
      "cons": ["Expensive", "Smaller hospital network", "Not available under 45"]
  },
  {
      "id": 7,
      "link": "https://www.bajajallianz.com/health-insurance-plans/health-guard.html",
      "name": "Bajaj Allianz Health Guard",
      "insurer": "Bajaj Allianz",
      "type": "Standard",
      "is_family_floater": False,
      "annual_premium": 7200,
      "premium_breakdown": { "base": 6101, "gst": 1099, "total": 7200 },
      "coverage": 750000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 93,
      "hospital_network_count": 8000,
      "restoration_benefit": True,
      "ideal_vector": [30, 23.0, 600000, 700, 0, 5.4, 115, 0, 0, 0],
      "coverage_highlights": ["Organ donor expenses", "Bariatric surgery covered", "Ayurvedic treatment"],
      "exclusions": ["Maternity", "Adventure sports", "Weight loss treatments"],
      "pros": ["Affordable", "540 day-care procedures", "Large hospital network"],
      "cons": ["No restore benefit", "Limited OPD"]
  },
  {
      "id": 8,
      "link": "https://www.icicilombard.com/health-insurance/complete-health-insurance",
      "name": "ICICI Lombard Complete Health",
      "insurer": "ICICI Lombard",
      "type": "Standard",
      "is_family_floater": False,
      "annual_premium": 8800,
      "premium_breakdown": { "base": 7457, "gst": 1343, "total": 8800 },
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 97,
      "hospital_network_count": 7500,
      "restoration_benefit": True,
      "ideal_vector": [35, 24.0, 800000, 900, 0, 5.5, 120, 0, 0, 0],
      "coverage_highlights": ["Wellness program", "Free health checkup", "Reset benefit"],
      "exclusions": ["Maternity", "Cosmetic surgery", "Self-inflicted injuries"],
      "pros": ["97% claim settlement ratio", "Telemedicine included", "Wellness rewards"],
      "cons": ["Standard 2-year wait", "Nothing exceptional for chronic conditions"]
  },
  {
      "id": 9,
      "link": "https://www.adityabirlacapital.com/healthinsurance/activ-health-insurance-plan",
      "name": "Aditya Birla Activ One",
      "insurer": "Aditya Birla",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 13200,
      "premium_breakdown": { "base": 11186, "gst": 2014, "total": 13200 },
      "coverage": 2000000,
      "pre_existing_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Any Room",
      "no_claim_bonus_pct": 50,
      "claim_settlement_ratio": 94,
      "hospital_network_count": 10500,
      "restoration_benefit": True,
      "ideal_vector": [32, 22.0, 1200000, 1300, 0, 5.1, 110, 0, 0, 0],
      "coverage_highlights": ["Chronic management program", "OPD cover", "100% reload of sum insured"],
      "exclusions": ["Maternity (unless addon selected)", "Hazardous sports"],
      "pros": ["Fitness discount up to 10%", "OPD up to ₹15,000/year", "Only 1-year pre-existing wait"],
      "cons": ["Fitness tracking mandatory for discount", "Higher premium"]
  },
  {
      "id": 10,
      "link": "https://www.manipalcigna.com/health-insurance/prime-senior",
      "name": "ManipalCigna Prime Senior",
      "insurer": "ManipalCigna",
      "type": "Senior",
      "is_family_floater": False,
      "annual_premium": 22000,
      "premium_breakdown": { "base": 18644, "gst": 3356, "total": 22000 },
      "coverage": 2500000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": False,
      "hypertension_day1": True,
      "min_age": 56,
      "max_age": 80,
      "copayment_pct": 20,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 91,
      "hospital_network_count": 8500,
      "restoration_benefit": True,
      "ideal_vector": [65, 28.0, 1000000, 2500, 0, 6.2, 145, 0, 1, 2],
      "coverage_highlights": ["Guaranteed issuance", "Day 1 coverage for hypertension", "Premium waiver benefit"],
      "exclusions": ["Certain pre-existing conditions have waiting periods", "Unproven treatments"],
      "pros": ["Hypertension from Day 1", "₹25L coverage", "Home care included"],
      "cons": ["Only for 56+", "Diabetes still 1-year wait", "Most expensive"]
  },
  {
      "id": 11,
      "link": "https://www.tataaig.com/health-insurance/critical-illness-insurance",
      "name": "Tata AIG CritiCare",
      "insurer": "Tata AIG",
      "type": "Critical Illness",
      "is_family_floater": False,
      "annual_premium": 6500,
      "premium_breakdown": { "base": 5508, "gst": 992, "total": 6500 },
      "coverage": 1500000,
      "pre_existing_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "N/A",
      "no_claim_bonus_pct": 0,
      "claim_settlement_ratio": 95,
      "hospital_network_count": 7200,
      "restoration_benefit": False,
      "ideal_vector": [45, 29.0, 1200000, 800, 1, 5.8, 130, 0, 1, 1],
      "coverage_highlights": ["Lump sum payout upon diagnosis", "Covers 11 critical illnesses", "Second medical opinion"],
      "exclusions": ["Illness diagnosed within first 90 days", "Self-inflicted injuries"],
      "pros": ["Lump sum paid on diagnosis", "Covers income loss during treatment", "Cheap premium"],
      "cons": ["Doesn't pay regular hospital bills", "4-year wait for pre-existing"]
  },
  {
      "id": 12,
      "link": "https://licindia.in/lic-s-tech-term-plan",
      "name": "LIC Tech Term",
      "insurer": "LIC",
      "type": "Term Life",
      "is_family_floater": False,
      "annual_premium": 8000,
      "premium_breakdown": { "base": 6779, "gst": 1221, "total": 8000 },
      "coverage": 5000000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 60,
      "copayment_pct": 0,
      "room_rent_limit": "N/A",
      "no_claim_bonus_pct": 0,
      "claim_settlement_ratio": 98,
      "hospital_network_count": 0,
      "restoration_benefit": False,
      "ideal_vector": [35, 24.0, 1000000, 800, 0, 5.4, 120, 0, 0, 0],
      "coverage_highlights": ["Pure life cover", "Special rates for women", "Tax benefits under Section 80C"],
      "exclusions": ["Suicide within first year"],
      "pros": ["Massive ₹50L life cover", "Online-only no commission", "Nominee gets full payout"],
      "cons": ["Pays nothing if alive", "No chronic condition coverage", "No hospital bills paid"]
  },
  {
      "id": 13,
      "link": "https://www.nivabupa.com/health-insurance/heartbeat-family-health-insurance.html",
      "name": "Max Bupa Heartbeat",
      "insurer": "Max Bupa",
      "type": "Comprehensive",
      "is_family_floater": False,
      "annual_premium": 15000,
      "premium_breakdown": { "base": 12711, "gst": 2289, "total": 15000 },
      "coverage": 3000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Any Room",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 90,
      "hospital_network_count": 8000,
      "restoration_benefit": True,
      "ideal_vector": [40, 26.0, 2000000, 1500, 0, 5.6, 125, 0, 0, 1],
      "coverage_highlights": ["Maternity benefits", "International cover", "OPD treatment"],
      "exclusions": ["Cosmetic treatments", "Dental care (unless accidental)"],
      "pros": ["Maternity coverage included", "International treatments covered", "High limit"],
      "cons": ["Premium is on the higher side", "Maternity has 2-year waiting period"]
  },
  {
      "id": 14,
      "link": "https://www.sbigeneral.in/health-insurance/arogya-premier-policy",
      "name": "SBI General Arogya Premier",
      "insurer": "SBI General",
      "type": "Standard",
      "is_family_floater": False,
      "annual_premium": 10500,
      "premium_breakdown": { "base": 8898, "gst": 1602, "total": 10500 },
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 94,
      "hospital_network_count": 6000,
      "restoration_benefit": True,
      "ideal_vector": [38, 25.0, 900000, 1100, 0, 5.5, 122, 0, 0, 0],
      "coverage_highlights": ["No pre-policy medical check-up", "Coverage for HIV/AIDS", "Mental illness covered"],
      "exclusions": ["Maternity", "Unproven treatments", "Substance abuse"],
      "pros": ["SBI trust factor", "Wide network in tier-2/3 cities", "Automatic reinstatement"],
      "cons": ["Slower claims processing", "No Day 1 covers for chronic"]
  },
  {
      "id": 15,
      "link": "https://www.careinsurance.com/product/care-freedom",
      "name": "Religare Health Care Freedom",
      "insurer": "Care Health (Religare)",
      "type": "Senior",
      "is_family_floater": False,
      "annual_premium": 19500,
      "premium_breakdown": { "base": 16525, "gst": 2975, "total": 19500 },
      "coverage": 500000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 50,
      "max_age": 85,
      "copayment_pct": 20,
      "room_rent_limit": "1% of Sum Insured",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 95,
      "hospital_network_count": 11500,
      "restoration_benefit": False,
      "ideal_vector": [70, 26.0, 500000, 2000, 0, 6.5, 140, 1, 1, 2],
      "coverage_highlights": ["No pre-policy medical checkup", "Annual health check-up", "Consumables covered"],
      "exclusions": ["Injuries from hazardous sports", "Self-inflicted injuries"],
      "pros": ["No pre-policy medical checkup", "Covers up to age 85", "Domiciliary care"],
      "cons": ["Co-payment of 20% on all claims", "Low coverage for the price"]
  },

  # --- NEW: FAMILY FLOATER PLANS ---
  {
      "id": 16,
      "link": "https://www.starhealth.in/health-insurance/family-health-optima-insurance-plan",
      "name": "Star Family Health Optima",
      "insurer": "Star Health",
      "type": "Comprehensive",
      "is_family_floater": True,
      "annual_premium": 16000,
      "premium_breakdown": { "base": 13559, "gst": 2441, "total": 16000 },
      "coverage": 1000000,
      "pre_existing_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "max_family_size": 6,
      "child_age_limit": 25,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 25,
      "claim_settlement_ratio": 89,
      "hospital_network_count": 9800,
      "restoration_benefit": True,
      "ideal_vector": [35, 24.0, 1000000, 1500, 0, 5.4, 115, 0, 0, 0],
      "coverage_highlights": ["Covers self, spouse, and up to 3 children", "Auto restoration of sum insured", "Newborn baby cover"],
      "exclusions": ["Maternity", "Pre-existing diseases before 4 years", "Cosmetic surgery"],
      "pros": ["Great for families", "3x auto restoration", "Wide hospital network"],
      "cons": ["4-year pre-existing wait", "Co-payment applies after age 61"]
  },
  {
      "id": 17,
      "link": "https://www.hdfcergo.com/health-insurance/optima-restore",
      "name": "HDFC Optima Restore Family",
      "insurer": "HDFC ERGO",
      "type": "Comprehensive",
      "is_family_floater": True,
      "annual_premium": 12500,
      "premium_breakdown": { "base": 10593, "gst": 1907, "total": 12500 },
      "coverage": 1500000,
      "pre_existing_wait_years": 3,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "max_family_size": 4,
      "child_age_limit": 25,
      "copayment_pct": 0,
      "room_rent_limit": "No Limit",
      "no_claim_bonus_pct": 50,
      "claim_settlement_ratio": 97,
      "hospital_network_count": 13000,
      "restoration_benefit": True,
      "ideal_vector": [40, 25.0, 1500000, 1200, 0, 5.5, 120, 0, 0, 0],
      "coverage_highlights": ["Multiplier benefit increases coverage 100%", "Restore benefit instantly available", "Preventive health check-up"],
      "exclusions": ["Maternity", "Obesity treatments", "Self-inflicted injuries"],
      "pros": ["Excellent claim settlement", "No room rent capping", "Bonus multiplies cover quickly"],
      "cons": ["3-year pre-existing wait", "Premium on higher side"]
  },
  {
      "id": 18,
      "link": "https://www.careinsurance.com/product/heart-health-insurance",
      "name": "Care Health Family Heart",
      "insurer": "Care Health",
      "type": "Comprehensive",
      "is_family_floater": True,
      "annual_premium": 18500,
      "premium_breakdown": { "base": 15678, "gst": 2822, "total": 18500 },
      "coverage": 2500000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": True,
      "hypertension_day1": True,
      "min_age": 18,
      "max_age": 65,
      "max_family_size": 6,
      "child_age_limit": 25,
      "copayment_pct": 0,
      "room_rent_limit": "Single Private",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 95,
      "hospital_network_count": 11500,
      "restoration_benefit": True,
      "ideal_vector": [45, 27.0, 2000000, 1800, 0, 6.5, 130, 1, 1, 1],
      "coverage_highlights": ["Covers cardiac conditions from day 1", "Day 1 coverage for hypertension/diabetes", "Annual cardiac health check-up"],
      "exclusions": ["Maternity", "Non-cardiac pre-existing conditions (2 yr wait)", "Cosmetic surgery"],
      "pros": ["Excellent for families with heart history", "High coverage", "Day 1 chronic covers"],
      "cons": ["Expensive", "Co-payment applies to some procedures"]
  },
  {
      "id": 19,
      "link": "https://www.bajajallianz.com/health-insurance-plans/family-health-insurance.html",
      "name": "Bajaj Allianz Family Floater",
      "insurer": "Bajaj Allianz",
      "type": "Standard",
      "is_family_floater": True,
      "annual_premium": 9800,
      "premium_breakdown": { "base": 8305, "gst": 1495, "total": 9800 },
      "coverage": 750000,
      "pre_existing_wait_years": 3,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "max_family_size": 4,
      "child_age_limit": 25,
      "copayment_pct": 10,
      "room_rent_limit": "₹5,000/day",
      "no_claim_bonus_pct": 10,
      "claim_settlement_ratio": 93,
      "hospital_network_count": 8000,
      "restoration_benefit": False,
      "ideal_vector": [35, 24.0, 800000, 900, 0, 5.5, 120, 0, 0, 0],
      "coverage_highlights": ["Affordable family cover", "Maternity expenses (with waiting period)", "Ayurvedic treatments"],
      "exclusions": ["Cosmetic surgeries", "Hazardous sports", "Unproven treatments"],
      "pros": ["Budget-friendly", "Maternity coverage", "Wide hospital network"],
      "cons": ["10% co-payment", "Lower room rent limit", "3-year wait"]
  },
  {
      "id": 20,
      "link": "https://www.nivabupa.com/health-insurance/heartbeat-family-health-insurance.html",
      "name": "Niva Bupa Family First",
      "insurer": "Niva Bupa",
      "type": "Comprehensive",
      "is_family_floater": True,
      "annual_premium": 21000,
      "premium_breakdown": { "base": 17797, "gst": 3203, "total": 21000 },
      "coverage": 3000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "max_family_size": 5,
      "child_age_limit": 25,
      "copayment_pct": 0,
      "room_rent_limit": "No Limit",
      "no_claim_bonus_pct": 20,
      "claim_settlement_ratio": 92,
      "hospital_network_count": 10000,
      "restoration_benefit": True,
      "ideal_vector": [42, 26.0, 2500000, 2000, 0, 5.6, 125, 0, 0, 0],
      "coverage_highlights": ["Individual base cover + floater pool", "No room rent capping", "Maternity and newborn cover"],
      "exclusions": ["Hazardous sports", "Self-inflicted injury", "Unproven treatments"],
      "pros": ["Unique base + floater structure", "High total coverage", "Great for larger families"],
      "cons": ["Very expensive", "Complex coverage structure to understand"]
  },


]

import json
import os

# Load dynamically from data.json in workspace root
json_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data.json"))

try:
    with open(json_path, "r", encoding="utf-8") as f:
        appended_plans = [p for p in json.load(f) if p.get("id", 0) > 20]
    INSURANCE_PLANS.extend(appended_plans)
except Exception as e:
    print(f"[ERROR] Failed to load INSURANCE_PLANS from {json_path}: {e}")
